const valid=new Map(projects.map(p=>[p.id,p]));
const requested=[...new Set((new URLSearchParams(location.search).get('order')||'').split(','))].filter(id=>valid.has(id));
let order=[...requested,...projects.map(p=>p.id).filter(id=>!requested.includes(id))];
const list=document.getElementById('order-list'),field=document.getElementById('share-url'),status=document.getElementById('status');
function render(focus){list.replaceChildren();order.forEach((id,i)=>{const row=document.createElement('li');row.className='order-row';const label=document.createElement('span');label.textContent=`${i+1}. ${valid.get(id).title}`;row.append(label);const controls=document.createElement('div');controls.className='controls';for(const [text,delta] of [['Up',-1],['Down',1]]){const button=document.createElement('button');button.textContent=text;button.disabled=i+delta<0||i+delta>=order.length;button.dataset.key=id+text;button.setAttribute('aria-label',`Move ${valid.get(id).title} ${text.toLowerCase()}`);button.onclick=()=>{[order[i],order[i+delta]]=[order[i+delta],order[i]];render(id+text);status.textContent=`${valid.get(id).title} moved to position ${i+delta+1}.`;};controls.append(button);}row.append(controls);list.append(row);});const url=new URL('./',location.href);url.searchParams.set('order',order.join(','));field.value=url.href;document.getElementById('preview').href=url.href;const edit=new URL(location.href);edit.searchParams.set('order',order.join(','));history.replaceState(null,'',edit);if(focus){const target=[...list.querySelectorAll('button')].find(b=>b.dataset.key===focus);if(target&&!target.disabled)target.focus();else target?.parentElement.querySelector('button:not(:disabled)')?.focus();}}
document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(field.value);status.textContent='Link copied. This link opens your chosen order.';}catch{field.focus();field.select();status.textContent='Select and copy the link above.';}};
document.getElementById('reset').onclick=()=>{order=projects.map(p=>p.id);render();status.textContent='Default order restored.';};
render();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'configure_project_order',description:'Set the visible project order and return its portfolio URL. Does not publish changes or change site access.',inputSchema:{type:'object',properties:{projectIds:{type:'array',items:{type:'string'},minItems:projects.length,maxItems:projects.length,uniqueItems:true}},required:['projectIds'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const next=input?.projectIds;if(!Array.isArray(next)||next.length!==projects.length||new Set(next).size!==projects.length||next.some(id=>!valid.has(id)))throw new Error('Provide every valid project ID exactly once.');order=[...next];render();return {projectIds:[...order],url:field.value};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
