const fs=require('fs'),vm=require('vm');
const file='portfolio/dist/projects.js',ctx={window:{}};vm.runInNewContext(fs.readFileSync(file,'utf8'),ctx);const projects=ctx.window.projects;
for(const id of ['narrative','shoulder','throwing','stepping','tree']){
 const p=projects.find(p=>p.id===id);
 p.role='Design & Implementation';
 p.contribution='Application design, implementation, system integration, and version control within a collaborative team.';
 p.sections.unshift(['My contribution','I contributed across application design and implementation, combining systems I built with work from teammates into the final build. I also handled version control and helped shape the overall interaction design.']);
}
const set=(id,process)=>projects.find(p=>p.id===id).process=process;
set('narrative',{title:'From story prototype to adaptive responses',text:'The team first tested the story in Twine with four participants, checking whether the flashbacks and their triggers made sense. Feedback supported the structure while highlighting some confusion at the beginning. The response map then connected dialogue choices and physiological states to the interrogator’s behaviour.',image:'assets/process-narrative.jpg',alt:'Team design diagram mapping dialogue choices and physiological states to four interrogator response styles.'});
set('asteroids',{title:'From a physical gesture to an in-game action',text:'I placed the orientation sensor on the back of the hand, the flex sensor along a finger, and the firing button within thumb reach. The glove sends input through Arduino to Unity. Deadzones and smoothing reduce jitter before those signals control steering, throttle, and shooting. Sensor drift and the wired connection remain limitations; a keyboard comparison is future work.',image:'assets/process-glove.jpg',alt:'The custom glove prototype with its sensors, wiring, Arduino, and thumb button.'});
set('throwing',{title:'Making the throw more predictable',text:'The team compared a custom interaction with Unity’s default throwing. A crosshair positioned in front of the non-throwing hand provides an explicit target, while movement magnitude controls throwing speed. Two participants scored higher with the custom technique across five trials each. This is an early usability result, not evidence of general performance.',image:'assets/process-throwing.jpg',alt:'Prototype screenshot showing the crosshair used to guide throws.'});
set('tree',{title:'Connecting breathing to the environment',text:'The team linked live respiration input to environmental growth and visual feedback. Distant trees react later than nearby trees, making the effect spread outward. Animated bark used a flipbook shader instead of video textures to address mapping and performance constraints. These choices connect the visual design to the practical requirements of a VR build.',image:'assets/process-tree.jpg',alt:'Team system diagram connecting physiological input, the VR environment, and intended experience outcomes.'});
set('stepping',{title:'Three approaches to foot tracking',text:'The team tried Azure Kinect, then Vive trackers, before attaching Quest 3 controllers to the feet. Kinect struggled with occlusion and fast movement; Vive trackers added calibration and passthrough compatibility problems. Quest controllers simplified setup and supported both VR and AR. Early slip-on mounts were refined into elastic and Velcro attachments for participants’ own shoes.',image:'assets/process-stepping.jpg',alt:'Prototype mounting arrangement for attaching a Quest controller to footwear.'});
set('shoulder',{title:'Making exercise guidance visible',text:'The team combined an instructor avatar, a virtual mirror, and movement feedback to support guided exercise. The prototype makes repetition count and arm elevation visible during the task. Pilot feedback highlighted exercise variety and customisation as priorities for a future iteration.',image:'assets/process-shoulder.jpg',alt:'Exercise prototype showing repetition count and arm-elevation feedback.'});
fs.writeFileSync(file,'window.projects = '+JSON.stringify(projects,null,2)+';\n');
for(const [src,dest] of [['extra-0-37-0.jpg','narrative'],['2-4-1.jpg','glove'],['1-2-1.jpg','throwing'],['0-5-0.jpg','tree'],['stepping-mount-0.jpg','stepping'],['3-2-1.jpg','shoulder']])fs.copyFileSync('research/'+src,'portfolio/dist/assets/process-'+dest+'.jpg');
const appFile='portfolio/dist/app.js';let app=fs.readFileSync(appFile,'utf8');const anchor="${p.video?`<div class=\"video-wrap\"";
if(!app.includes(anchor))throw Error('Process insertion anchor missing');
app=app.replace(anchor,"${p.process?`<section class=\"process\"><div><p class=\"eyebrow\">Design process</p><h4>${escapeHTML(p.process.title)}</h4><p>${escapeHTML(p.process.text)}</p></div><a href=\"${p.process.image}\" target=\"_blank\" rel=\"noopener\" aria-label=\"Open process image for ${escapeHTML(p.title)}\"><img src=\"${p.process.image}\" alt=\"${escapeHTML(p.process.alt)}\" loading=\"lazy\"></a></section>`:''}"+anchor);
fs.writeFileSync(appFile,app);
fs.appendFileSync('portfolio/dist/style.css','\n.process{grid-column:1/-1;display:grid;grid-template-columns:1fr 1fr;gap:36px;align-items:center;border-top:1px solid var(--line);padding-top:28px}.process .eyebrow{font-size:12px;color:var(--accent);margin-bottom:10px}.process img{display:block;width:100%;height:auto;max-height:380px;object-fit:contain;border-radius:4px;background:var(--surface)}.process a{display:block}.process h4{font-size:20px}@media(max-width:750px){.process{grid-template-columns:1fr;gap:22px}}\n');
const index='portfolio/dist/index.html';let html=fs.readFileSync(index,'utf8');html=html.replace('I design and build interactive experiences, from games and XR to custom hardware and research prototypes.','I design and build interactive experiences, from games and XR to custom hardware and research prototypes. I bring design, code, and team-built systems together into working applications.');fs.writeFileSync(index,html);
